INSERT INTO VEICULO(MODELO, ANO, PLACA, MARCA) VALUES ('CIVIC SI', '2008', 'HFL9182', 'HONDA');
INSERT INTO VEICULO(MODELO, ANO, PLACA, MARCA) VALUES ('320I MOTORSPORT', '2021', 'GHD2849', 'BMW');
INSERT INTO VEICULO(MODELO, ANO, PLACA, MARCA) VALUES ('MONZA TUBARÃO' , '1990', 'IFL9290' , 'CHEVROLET');